### ISSUE TITLE
Pass in Custom Headers for Authentication

### ISSUE THREAD

**Issue by urbinaalex17** [Electronic-Signatures-Industries/xdv-universal-wallet#15]
To use any IPFS cloud provider, we need to pass in custom headers like authorization with JWT or API Keys, which currently is not supported.

This library uses the `ipfs-http-client` to interact with IPFS, so here is what should be done. https://www.npmjs.com/package/ipfs-http-client#custom-headers

**Comment by molekilla** [comment]
you need to override and customize on your side
